name: "Bazel setup"
description: "Sets up necessary steps for Bazel"

inputs:
  nativelink-api-key:
    description: "API key for NativeLink remote cache service"
    required: true

runs:
  using: composite
  steps:
    - uses: bazel-contrib/setup-bazel@0.8.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: false
        # Share repository cache between workflows.
        repository-cache: false
        bazelrc: |
          import %workspace%/.aspect/bazelrc/ci.bazelrc
          common --verbose_failures
          build --show_progress_rate_limit=0.2
          build --curses=no
          build --remote_download_toplevel
          build --remote_upload_local_results
          build --remote_local_fallback
          build --grpc_keepalive_time=30s
          build --remote_cache=grpcs://cas-hjellek.build-faster.nativelink.net
          build --remote_header=x-nativelink-api-key=${{ inputs.nativelink-api-key }}
          build --bes_backend=grpcs://bes-hjellek.build-faster.nativelink.net
          build --bes_header=x-nativelink-api-key=${{ inputs.nativelink-api-key }}
          build --remote_timeout=600
